---
# tasks file for etcd

# - name: download etcd
#   get_url:
#     url: https://github.com/etcd-io/etcd/releases/download/v3.5.7/etcd-v3.5.7-linux-amd64.tar.gz
#     dest: /tmp

# - name: untar etcd
#   unarchive:
#     src: /tmp/etcd-v3.5.7-linux-amd64.tar.gz
#     dest: /tmp
#     remote_src: true

- name: copy etcd binary to /usr/local/bin
  copy:
    src: "{{ item }}"
    mode: 0755
    dest: /usr/local/bin/
  with_fileglob:
    - "/home/almalinux/ansible/roles/etcd/files/etcd*"

- name: make dirs for etcd
  file:
    path: /etc/etcd
    state: directory
    mode: 755
  
- name: create etcd group
  group:
    name: etcd
    state: present
    system: true

- name: create etcd user
  user:
    name: etcd
    state: present
    system: true
    shell: /sbin/nologin
    home: /var/lib/etcd/{{ inventory_hostname }}.etcd

- name: chown /var/lib/etcd
  file:
    path: /var/lib/etcd/{{ inventory_hostname }}.etcd
    state: directory
    owner: etcd
    group: etcd
    mode: 0775
    recurse: true

- name: copy etcd config
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf.yaml

- name: copy service file
  copy:
    src: files/etcd.service
    dest: /etc/systemd/system/etcd.service
  notify: restart etcd
